# Generated by Django 4.2.17 on 2025-02-05 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='level',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
