# Generated by Django 4.2.17 on 2025-02-10 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prajnayana_dashboard', '0004_alter_journalentry_mood'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeHub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('date_added', models.DateField(auto_now_add=True)),
                ('level', models.IntegerField(default=1)),
                ('image_url', models.URLField()),
                ('category', models.CharField(choices=[('Mindfulness Techniques', 'Mindfulness Techniques'), ('Emotional Resilience', 'Emotional Resilience'), ('Self-Awareness', 'Self Awareness'), ('Personal Growth', 'Personal Growth'), ('Community Stories', 'Community Stories')], max_length=255)),
            ],
        ),
    ]
