# Generated by Django 4.2.17 on 2025-02-11 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prajnayana_dashboard', '0006_visionboard'),
    ]

    operations = [
        migrations.AddField(
            model_name='visionboard',
            name='favorite',
            field=models.BooleanField(default=False),
        ),
    ]
