# Generated by Django 4.2.17 on 2025-04-19 22:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('prajnayana_dashboard', '0010_alter_habits_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habittracking',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
