# Generated by Django 4.2.17 on 2025-04-19 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prajnayana_dashboard', '0011_alter_habittracking_date_alter_journalentry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visionboard',
            name='category',
            field=models.CharField(choices=[('Quote', 'Quote'), ('Affirmation', 'Affirmation'), ('Goal', 'Goal'), ('Prompt', 'Prompt')], max_length=255),
        ),
    ]
